<?php
// $Id$

/**
* Implementation of hook_menu().
*/
function gss_menu() {
  $items = array();
  
  $items['admin/config/search/gss'] = array(
    'title' => 'Google Site Search',
    'description' => 'Google Site Search settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gss_settings'),
    'access arguments' => array('administer site settings'),
  );
  
//  $items['google-search'] = array(
//    'title' => t('Search'),
//    'page callback' => 'search',
//    'access arguments' => array('access content'),
//    'type' => MENU_CALLBACK,
//  );
//  
//  $items['google-search/%'] = array(
//    'title' => t('Search results'),
//    'page callback' => 'gss_search_results',
//    'page arguments' => array(1),
//    'access arguments' => array('access content'),
//    'type' => MENU_CALLBACK,
//  );
  
  return $items;
}
/**
 * Implements hook_theme().
 */
function gss_theme($existing, $type, $theme, $path) {
  return array(
    'gss_result' => array(
      'variables' => array('result' => NULL, 'module' => NULL),
      'file' => 'gss.theme.inc',
      'template' => 'gss-result',
    ),
    'gss_results' => array(
      'variables' => array('results' => NULL, 'module' => NULL),
      'file' => 'gss.theme.inc',
      'template' => 'gss-results',
    ),
  );
}
/**
* Module settings.
*/
function gss_settings() {
  $form = array();
  
  $form['gss_api_key'] = array(
    '#title' => t('API Key'),
    '#type' => 'textfield',
    '#description' => t('Your Google Site Search API key.'),
    '#default_value' => variable_get('gss_api_key', ''),
    '#required' => TRUE,
  );
  $form['gss_language'] = array(
    '#title' => t('Language'),
    '#type' => 'textfield',
    '#description' => t('The language to search. Write the language code with two letters. Ex: for "english", write "en"; for "Chinese (Simplified)"'),
    '#default_value' => variable_get('gss_language', ''),
    '#size' => 5,
    '#max_length' => 5,
  );
  $form['gss_default_language'] = array(
    '#title' => t('Language'),
    '#type' => 'checkbox',
    '#description' => t('The language to search. Write the language code with two letters. Ex: for "english", write "en".'),
    '#default_value' => variable_get('gss_default_language', FALSE),
    '#size' => 2,
    '#max_length' => 2,
  );
  $form['gss_page_size'] = array(
    '#title' => t('Page size'),
    '#type' => 'textfield',
    '#description' => t('Number of results to display per page.'),
    '#default_value' => variable_get('gss_page_size', 20),
    '#size' => 5,
    '#max_length' => 5,
  );
  $form['gss_results_tab'] = array(
    '#title' => t('Search results tab name'),
    '#type' => 'textfield',
    '#maxlength' => 50,
    '#size' => 60,
    '#description' => t('Enter a custom name of the tab where search results are displayed (defaults to %google).', array('%google' => t('Google Search'))),
    '#default_value' => variable_get('gss_results_tab', ''),
  );
  
  return system_settings_form($form);
}

/**
* Implementation of hook_block().
*/
function gss_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => t('Google Site Search'),
      'weight' => 0,
      'status' => 0,
    );

    return $blocks;
  }
  else if ($op == 'view') {
    $block = array(
      'subject' => t('Search'),
      'content' => drupal_get_form('gss_search_form'),
    );

    return $block;
  }
}
/**
* Search results page.
*/
function gss_search_results($query) {

  // Include dependencies.
  module_load_include('inc', 'gss', 'includes/GoogleSiteSearch');
  // Make query safe.
  $query = check_plain($query);
  // Init GoogleSiteSearch object.
  $gss = new GoogleSiteSearch($query, variable_get('gss_api_key', ''));
  // Get current page.
  $page = isset($_GET['page']) ? intval($_GET['page']) : 1;
  // Init results variable.
  $results = null;
  // Set the number of results per page.
  $gss->SetPageSize(variable_get('gss_page_size', 20));
  // Perform search.
  try {
    $results = $gss->GetSearchResults($page);
  }
  catch(Exception $e) {
     watchdog('gss', $e, NULL, WATCHDOG_ERROR);
     drupal_set_message(t('Sorry, the search function is unavailable at this time.'));
     exit();
  }
  // Get search summary.
  $total_results = $gss->GetTotalResults();
  $end_pos = $gss->GetCurrentPage() * $gss->GetPageSize();
  $start_pos = $end_pos - $gss->GetPageSize() + 1;
  
  if ($end_pos > $total_results) {
    $end_pos = $total_results;
  }
  // Build output.
  if (!empty($results)) {
    $output = array();
    // Loop results.
    foreach ($results as $result) {
      $output[] = array(
        'link' => urldecode($result['url']),
        'title' => $result['title'],
        'snippet' => $result['description'],
        );
    }
  }
  else {
    $output[] = array(
        'link' => '',
        'title' => '',
        'snippet' => t('No results'),
        );
  }
  // Build URL to the pager  
  $destination = drupal_get_destination();  
  $url_parse = drupal_parse_url($destination['destination']);
  $url_parse['query']['page'] = '';
  $link = url($url_parse['path'], $url_parse);
  // Get searrch head
  $output['head'] = $gss->GetSearchHead();
  // Get pager
  $output['pager'] = $gss->GetPager($link);
  
  return $output;
}
/**
* Get class names for result item.
*/
function _gss_get_link_class($result) {
  $file_types = array('pdf', 'doc', 'docx', 'ppt', 'pptx', 'odt');
  $file = basename($result['url']);
  $ext = drupal_strtolower(substr($file, strrpos($file, '.') + 1));
  if (in_array($ext, $file_types)) {
    return 'filetype-'. $ext;
  }
  else {
    return 'filetype-page';
  }
}
/**
 * Implements hook_search_execute().
 */
function gss_search_execute($keys = NULL, $conditions = NULL) {
  if ($keys && !isset($_GET['query'])) {
    drupal_goto('search/google-search/'. $keys, array('query' => gss_build_query($keys)), 301);
  }
  return gss_search_results($keys);  
}
/**
 * Implements hook_search_info().
 */
function gss_search_info() {
  return array(
    'title' => gss_results_tab(),
    'path' => 'google-search',
    'conditions_callback' => 'gss_conditions_callback',
  );
}
/**
 * Search conditions callback.
 */
function gss_conditions_callback($keys) {
  $conditions = array();
  return $conditions;
}
/**
 * Return the Google Site Search tab title, either a setting or a translation.
 */
function gss_results_tab() {
  return ($var = variable_get('gss_results_tab', '')) ? $var : t('Google Search');
}
/**
 * Returns an array of any advanced settings which have been set.
 */
function gss_advanced_settings() {
  global $language;
  $settings = array();
  foreach (array('cr', 'gl', 'hl', 'ie', 'lr', 'oe', 'safe') as $parameter) {
    if ($setting = variable_get("google_cse_$parameter", '')) {
      $settings[$parameter] = $setting;
    }
  }
  if (variable_get('gss_locale_hl', '')) {
    $settings['hl'] = $language->language;
  }
  if (variable_get('gss_locale_lr', '')) {
    $settings['lr'] = 'lang_'. $language->language;
  }
  return $settings;
}
/**
 * Builds a query array based on Google Site Search settings.
 */
function gss_build_query($keys, $sitesearch = NULL, $here = TRUE) {
  return array(
    'query' => $keys,
    'cx' => variable_get('gss_api_key', ''),
    'cof' => $here ? variable_get('google_cse_cof_here', 'FORID:11') : variable_get('google_cse_cof_google', 'FORID:0'),
    'sitesearch' => isset($sitesearch) ? $sitesearch : '',
  ) + gss_advanced_settings();
}
/**
 * Adds custom submit handler for search form.
 */
function gss_form_search_form_alter(&$form, &$form_state, $form_id) {
  if ($form['module']['#value'] == 'gss') {
    if (variable_get('gss_results_gadget', 1)) {
      $form['basic']['op']['#suffix'] = theme('gss_results_gadget');
    }
    $form['#submit'][] = 'gss_search_form_submit';
    $form['#attributes']['class'][] = 'gss';
  }
}
/**
* Submit handler.
*/
function gss_search_form_submit($form, &$form_state) {
  $keys = $form_state['values']['processed_keys'];
  $sitesearch = isset($form_state['values']['sitesearch']) ? $form_state['values']['sitesearch'] : NULL;
  $form_state['redirect'] = array($form_state['redirect'], array('query' => google_cse_build_query($keys, $sitesearch)), 301);
}
/**
 * Implements hook_search_page().
 */
function gss_search_page($results) {
  $head = $results['head'];
  unset($results['head']);
  $pager = $results['pager'];
  unset($results['pager']);
  $output['prefix']['#markup'] = $head . '<ol class="google-search-results">';
  foreach ($results as $entry) {
    $output[] = array(
      '#theme' => 'gss_result', 
      '#result' => $entry, 
      '#module' => 'gss',
    );
  }
  $output['suffix']['#markup'] = '</ol>' . $pager;
  drupal_set_title(t('Search results'));
  return $output;
}










